<h2>Mentions Légales</h2>
<div class="page-content container px-4">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sit amet risus congue sem euismod eleifend in eu erat. In hendrerit elit ac diam ullamcorper, id tincidunt nunc luctus. Phasellus ac justo eget magna efficitur rhoncus. Phasellus luctus justo in rutrum dignissim. Donec dignissim odio nunc, quis pretium arcu vulputate non. Sed mollis massa vel tempus efficitur. Duis sit amet dolor vitae dolor volutpat laoreet. Phasellus ante lacus, pharetra non eros in, feugiat iaculis sem. Curabitur mollis ac odio vel efficitur. Quisque tincidunt ligula eu massa egestas, at blandit odio viverra. Phasellus massa odio, luctus id laoreet eu, interdum a ipsum. Pellentesque iaculis dolor turpis, at iaculis nisl tincidunt at.
    </p>
    <p>
        Nulla sodales arcu ante, porttitor volutpat lectus ultrices id. Integer sagittis porttitor vehicula. Sed vitae augue eget nisi eleifend accumsan. Etiam id sapien et nunc imperdiet laoreet. In quis rutrum nunc, id euismod ex. Nullam sit amet dapibus arcu. Etiam suscipit at tellus id commodo. Quisque accumsan pharetra neque quis efficitur. Sed pellentesque finibus efficitur. In volutpat risus vitae ligula condimentum, nec luctus elit vestibulum. Vestibulum gravida arcu nec ante eleifend, in cursus dolor tincidunt. Mauris in sem id urna bibendum sollicitudin sit amet sit amet dolor. Donec non tellus in enim lacinia dignissim. Cras odio ante, mattis at efficitur eu, eleifend id libero.
    </p>
    <p>
        Nullam semper ultrices purus quis feugiat. Morbi dignissim sodales ex. Proin id lacus vitae nunc tristique eleifend dignissim sed urna. Vivamus lectus odio, pulvinar non urna quis, eleifend fermentum ante. Integer ac magna in orci consequat feugiat a at mauris. In hac habitasse platea dictumst. Nam leo leo, volutpat vel dui vitae, venenatis egestas turpis. In in fermentum massa. Duis rutrum lectus luctus dictum pretium. Nulla sem justo, viverra rutrum sollicitudin at, euismod ornare velit. Sed tempor justo enim, in scelerisque nulla vestibulum vitae. Nullam porttitor, massa nec dapibus efficitur, mi est bibendum sem, ut elementum nulla arcu et libero. In vulputate, est vel molestie rutrum, ligula diam consectetur mi, ut mattis enim nulla non nisi. Nullam augue felis, auctor quis interdum ac, rutrum et magna. Etiam quis ligula nunc.
    </p>
    <p>
        Curabitur a tempus nisi. Nulla facilisi. Curabitur iaculis risus at ex commodo iaculis. Duis sagittis ante ac hendrerit semper. Sed nec accumsan arcu. Nulla et ipsum ex. In a pellentesque lectus. Fusce purus sapien, tempor et urna a, rutrum tempus justo. Morbi convallis risus est, a porta nibh pulvinar et. Donec eget lorem id nisi feugiat luctus id fermentum mi. Donec elementum turpis lorem, quis pellentesque dolor tincidunt eget. Donec eget risus sed libero ultrices vulputate nec ut mi. Duis congue tempus metus non viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    </p>
    <p>
        Aliquam erat volutpat. Proin consectetur ex non imperdiet porta. Fusce odio lacus, suscipit vitae ligula eget, imperdiet rutrum arcu. Morbi id dui risus. Phasellus dictum, mi porttitor scelerisque tincidunt, ipsum arcu porttitor tortor, ac molestie nisl ante consequat nunc. Aenean leo leo, vulputate vel tortor sed, fermentum eleifend tortor. Nullam massa est, rhoncus volutpat dictum eget, accumsan consectetur nisl. Nulla facilisi. Duis ut tortor ac lacus facilisis pulvinar at sollicitudin odio. Donec tincidunt diam at diam tincidunt ultricies.
    </p>
</div>
